language: node_js

node_js:
  - 9
  - 8
  
addons:
  apt:
    packages:
      - build-essential
      - git
      - gcc-4.8
      - g++-4.8
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libudev1
      - libudev-dev

install:
  - export CXX=g++-4.8

before_script:
  - npm install -g node-gyp
  - npm install node-hid --build-from-source
  - npm install

script:
  - npm test

cache:
  directories:
    - node_modules