version: 2
jobs:
  test-node-9:
    working_directory: ~/javascript-cli
    docker:
      - image: circleci/node:9.11-browsers
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |
            sudo apt-get update
            sudo apt-get -t jessie-backports install libudev-dev libusb-1.0-0-dev
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install global packages
          command: yarn global add node-gyp
      - run:
          name: Install HID packages
          command: yarn install node-hid --build-from-source
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: yarn test
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Depcheck
          command: yarn depcheck

workflows:
  version: 2
  test:
    jobs:
      - test-node-9
